version: '3.5'

services:     
  wolproxypyapi:
    image: bateman/wolproxypyapi:latest
    hostname: wolproxypyapi
    container_name: wolproxypyapi
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    ports:
      - 8000:80
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  wolproxypyweb:
    depends_on:
      - wolproxypyapi
    image: bateman/wolproxypyweb:latest
    hostname: wolproxypyweb
    container_name: wolproxypyweb
    restart: unless-stopped
    volumes:
      - ./logs:/logs
      - ./db:/db
    ports:
      - 5000:80
    env_file: .env
    environment:
      - API_PROTO=${API_PROTO}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET})
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 

networks:
  app-network:
    driver: bridge
